using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Options;
using static System.Net.Mime.MediaTypeNames;
using System.Data;
using System.IO;
using System.Reflection.PortableExecutable;
using System;

namespace DatasheetService.KSBasePayloadDTO
{
    public class ConstantTexts
    {
        public CommonProperties Yes { get; set; }
        public CommonProperties With_Handwheel { get; set; }
        public CommonProperties With_Electric_Actuator { get; set; }
        public CommonProperties Wear_Ring_Suction_Side { get; set; }
        public CommonProperties Wear_Ring_Discharge_Side { get; set; }
        public CommonProperties Volute_Casing_100 { get; set; }
        public CommonProperties Volute_Casing { get; set; }
        public CommonProperties Visual_Inspection_Witnessed { get; set; }
        public CommonProperties Visual_Inspection { get; set; }
        public CommonProperties Vibration_Test_Wittnessed { get; set; }
        public CommonProperties Vibration_Test { get; set; }
        public CommonProperties Version_No { get; set; }
        public CommonProperties Variant_Z10 { get; set; }
        public CommonProperties Variant_V10 { get; set; }
        public CommonProperties Variant_U51 { get; set; }
        public CommonProperties Variant_U50 { get; set; }
        public CommonProperties Variant_U22 { get; set; }
        public CommonProperties Variant_U21 { get; set; }
        public CommonProperties Variant_U20 { get; set; }
        public CommonProperties Variant_U14 { get; set; }
        public CommonProperties Variant_U12 { get; set; }
        public CommonProperties Variant_U11 { get; set; }
        public CommonProperties Variant_U10 { get; set; }
        public CommonProperties Variant_T11 { get; set; }
        public CommonProperties Variant_T10 { get; set; }
        public CommonProperties Variant_Shaft_Seal { get; set; }
        public CommonProperties Variant_Services { get; set; }
        public CommonProperties Variant_Plates { get; set; }
        public CommonProperties Variant_Packing { get; set; }
        public CommonProperties Variant_Order_Document { get; set; }
        public CommonProperties Variant_N12 { get; set; }
        public CommonProperties Variant_N11 { get; set; }
        public CommonProperties Variant_Lifting { get; set; }
        public CommonProperties Variant_K60 { get; set; }
        public CommonProperties Variant_K50 { get; set; }
        public CommonProperties Variant_K10 { get; set; }
        public CommonProperties Variant_Hydraulic { get; set; }
        public CommonProperties Variant_G50 { get; set; }
        public CommonProperties Variant_G10 { get; set; }
        public CommonProperties Variant_F40 { get; set; }
        public CommonProperties Variant_F30 { get; set; }
        public CommonProperties Variant_F20 { get; set; }
        public CommonProperties Variant_F10 { get; set; }
        public CommonProperties Variant_Driver { get; set; }
        public CommonProperties Variant_D80 { get; set; }
        public CommonProperties Variant_D70 { get; set; }
        public CommonProperties Variant_D10 { get; set; }
        public CommonProperties Variant_Corrosion_Protection { get; set; }
        public CommonProperties Variant_Condition { get; set; }
        public CommonProperties Variant_Certificates { get; set; }
        public CommonProperties Variant_Casing_Impeller { get; set; }
        public CommonProperties Variant_Baseplate_Coupling_Bearing { get; set; }
        public CommonProperties Variant_B50 { get; set; }
        public CommonProperties Variant_B10 { get; set; }
        public CommonProperties Variant_A70 { get; set; }
        public CommonProperties Variant_A50 { get; set; }
        public CommonProperties Variant_A15 { get; set; }
        public CommonProperties Variant_A10 { get; set; }
        public CommonProperties Variant_A01 { get; set; }
        public CommonProperties Variant_A00 { get; set; }
        public CommonProperties Valve_Pressure { get; set; }
        public CommonProperties Valve_Material { get; set; }
        public CommonProperties Valve_Ends { get; set; }
        public CommonProperties Valve_Design { get; set; }
        public CommonProperties Valvedriver { get; set; }
        public CommonProperties User { get; set; }
        public CommonProperties Unit_Price { get; set; }
        public CommonProperties Unit_Design { get; set; }
        public CommonProperties Transmission_And_Battery_Unit { get; set; }
        public CommonProperties Total_Sum { get; set; }
        public CommonProperties Tightness_Test_Addition { get; set; }
        public CommonProperties Tightness_Complete_Valve { get; set; }
        public CommonProperties Test_Certification { get; set; }
        public CommonProperties Testing { get; set; }
        public CommonProperties Tensile_Test_At_Room_Temperature { get; set; }
        public CommonProperties Tensile_Test { get; set; }
        public CommonProperties Tender_Text { get; set; }
        public CommonProperties Technical_Data_Ksb_Guard_Gateway { get; set; }
        public CommonProperties Technical_Datasheet_Monitoring_Unit { get; set; }
        public CommonProperties Technical_Datasheet_Control_Unit_P10A { get; set; }
        public CommonProperties Technical_Datasheet_Control_Unit_L20A { get; set; }
        public CommonProperties Technical_Datasheet_Control_Unit_A75B { get; set; }
        public CommonProperties Technical_Datasheet_Control_Unit { get; set; }
        public CommonProperties Technical_Datasheet { get; set; }
        public CommonProperties Technical_Data { get; set; }
        public CommonProperties Supplementary_Drawing_Note { get; set; }
        public CommonProperties Suction_Side { get; set; }
        public CommonProperties Suction_Flange { get; set; }
        public CommonProperties Suction_Cover { get; set; }
        public CommonProperties Strip_Test_Witnessed { get; set; }
        public CommonProperties Strip_Test { get; set; }
        public CommonProperties Street { get; set; }
        public CommonProperties Standard { get; set; }
        public CommonProperties Speed_Curve { get; set; }
        public CommonProperties Special_Design { get; set; }
        public CommonProperties Soldtoparty { get; set; }
        public CommonProperties Shaft_Wo_Partno { get; set; }
        public CommonProperties Shaft_Seal_Auxiliary_System { get; set; }
        public CommonProperties Shaft_Sealing { get; set; }
        public CommonProperties Shaft_Protecting_Sleeve { get; set; }
        public CommonProperties Shaft { get; set; }
        public CommonProperties Services { get; set; }
        public CommonProperties Sensor_Unit { get; set; }
        public CommonProperties Sensor_Tbe { get; set; }
        public CommonProperties Sensors_To_Be_Evaluated { get; set; }
        public CommonProperties Seat_Tightness_Test_Addition { get; set; }
        public CommonProperties Seat_Tightness_Test { get; set; }
        public CommonProperties Seal_Cover { get; set; }
        public CommonProperties Sales_Document { get; set; }
        public CommonProperties Revision_No { get; set; }
        public CommonProperties Remarks { get; set; }
        public CommonProperties Recipient { get; set; }
        public CommonProperties Quantity { get; set; }
        public CommonProperties Pump_Feet_Pump_Stand_Or_Foundatation_Rail { get; set; }
        public CommonProperties Pump_Feet { get; set; }
        public CommonProperties Pumpdrivedesignfixtest { get; set; }
        public CommonProperties Pumpdrive2Eco { get; set; }
        public CommonProperties Pumpdrive2 { get; set; }
        public CommonProperties Pumpdrive { get; set; }
        public CommonProperties Project { get; set; }
        public CommonProperties Product_Properties { get; set; }
        public CommonProperties Pricesheet { get; set; }
        public CommonProperties Pressure_Test_Addition { get; set; }
        public CommonProperties Power_Drive_System { get; set; }
        public CommonProperties Position_No { get; set; }
        public CommonProperties Piping_Plan { get; set; }
        public CommonProperties Performance_Test { get; set; }
        public CommonProperties Performance_Curve_Pump { get; set; }
        public CommonProperties Parent { get; set; }
        public CommonProperties Parameterized_For_Driver { get; set; }
        public CommonProperties Page { get; set; }
        public CommonProperties Packing_Test { get; set; }
        public CommonProperties Packaging_Inspection_Witnessed { get; set; }
        public CommonProperties Packaging_Inspection { get; set; }
        public CommonProperties Packaging { get; set; }
        public CommonProperties P10A_Tendertext { get; set; }
        public CommonProperties P10A_Eco { get; set; }
        public CommonProperties P10Aeco_Tendertext { get; set; }
        public CommonProperties P10A { get; set; }
        public CommonProperties Outlet { get; set; }
        public CommonProperties Order_No { get; set; }
        public CommonProperties Order_Documentation { get; set; }
        public CommonProperties Order_Date { get; set; }
        public CommonProperties Order { get; set; }
        public CommonProperties Optional { get; set; }
        public CommonProperties Operating_Condition_Purchaser_Requirements { get; set; }
        public CommonProperties Operating_Conditions_Performance { get; set; }
        public CommonProperties Operatingpoint { get; set; }
        public CommonProperties Operatingdatapoint { get; set; }
        public CommonProperties Offer_No { get; set; }
        public CommonProperties Offer_Date { get; set; }
        public CommonProperties Offer { get; set; }
        public CommonProperties Object_No { get; set; }
        public CommonProperties Number_Of_Bolts { get; set; }
        public CommonProperties Npsh_Test_Witnessed { get; set; }
        public CommonProperties Npsh_Test { get; set; }
        public CommonProperties Nozzle_Connections_Pump { get; set; }
        public CommonProperties Note { get; set; }
        public CommonProperties Nominal_Size { get; set; }
        public CommonProperties Nominal_Pressure_Drilling_Pattern { get; set; }
        public CommonProperties Nominal_Pressure { get; set; }
        public CommonProperties Noise_Emission { get; set; }
        public CommonProperties No { get; set; }
        public CommonProperties Net_Weight { get; set; }
        public CommonProperties Nameplates { get; set; }
        public CommonProperties Motor_Options { get; set; }
        public CommonProperties Motor_Datasheet { get; set; }
        public CommonProperties Motor_Data { get; set; }
        public CommonProperties Motor_Casing_Cover_160 { get; set; }
        public CommonProperties Motor_Casing_Cover { get; set; }
        public CommonProperties Motor_Approvals { get; set; }
        public CommonProperties Motor { get; set; }
        public CommonProperties Miscellanous { get; set; }
        public CommonProperties Medium { get; set; }
        public CommonProperties Mat_Number { get; set; }
        public CommonProperties Matnr { get; set; }
        public CommonProperties Material_Inspection { get; set; }
        public CommonProperties Material_Design { get; set; }
        public CommonProperties Material_Certificates { get; set; }
        public CommonProperties Materials_With_Food_Contact { get; set; }
        public CommonProperties Materials { get; set; }
        public CommonProperties Marking_Nameplates { get; set; }
        public CommonProperties Mandotorydocuments { get; set; }
        public CommonProperties Longtextpd2Ifs_55_11 { get; set; }
        public CommonProperties Longtextpd2Ifs_15_45 { get; set; }
        public CommonProperties Longtextpd2Eco { get; set; }
        public CommonProperties Longtextpd2 { get; set; }
        public CommonProperties Lifting_Guide { get; set; }
        public CommonProperties Lifting_Equipment { get; set; }
        public CommonProperties Levelcontrol_Single { get; set; }
        public CommonProperties Levelcontrol_Double { get; set; }
        public CommonProperties Language { get; set; }
        public CommonProperties L { get; set; }
        public CommonProperties Kks_No { get; set; }
        public CommonProperties K { get; set; }
        public CommonProperties Item_Sum { get; set; }
        public CommonProperties Item_Quantity { get; set; }
        public CommonProperties Item_No { get; set; }
        public CommonProperties Item_Date { get; set; }
        public CommonProperties Item { get; set; }
        public CommonProperties Internal_Use_Only_Note { get; set; }
        public CommonProperties Internal_Calculation_Sheet { get; set; }
        public CommonProperties Installation_Plan_Note_Dimensions_Imperial { get; set; }
        public CommonProperties Installation_Plan_Note_Dimensions { get; set; }
        public CommonProperties Installation_Plan_Note2 { get; set; }
        public CommonProperties Installation_Plan_Note { get; set; }
        public CommonProperties Installation_Plan { get; set; }
        public CommonProperties Installation_Parts_Accessories { get; set; }
        public CommonProperties Installation_Parts { get; set; }
        public CommonProperties Inlet_Accessory_Suction { get; set; }
        public CommonProperties Inlet { get; set; }
        public CommonProperties Impeller_Wo_Partno { get; set; }
        public CommonProperties Impeller_Wear_Ring_Suction_Side { get; set; }
        public CommonProperties Impeller_Wear_Ring_Discharge_Side { get; set; }
        public CommonProperties Impeller_Fastening { get; set; }
        public CommonProperties Impeller { get; set; }
        public CommonProperties Impact_Test_Room_Temperature { get; set; }
        public CommonProperties Impact_Test_At_Different_Temperature { get; set; }
        public CommonProperties Image { get; set; }
        public CommonProperties Hydrostatic_Test_Product_Witnessed { get; set; }
        public CommonProperties Hydrostatic_Test_Product { get; set; }
        public CommonProperties Hydrostatic_Test_Pressure_Containing_Parts { get; set; }
        public CommonProperties Hydrostatic_Test_Parts { get; set; }
        public CommonProperties Hydrostatic_Test_Finished_Parts { get; set; }
        public CommonProperties Hydraulic_Performance_Test_Witnessed { get; set; }
        public CommonProperties Hydraulic_Performance_Test { get; set; }
        public CommonProperties Hydraulic_Operating_Data { get; set; }
        public CommonProperties Heat_Treatment { get; set; }
        public CommonProperties Headline_A11B { get; set; }
        public CommonProperties Hardness_Test { get; set; }
        public CommonProperties Guide_Wire { get; set; }
        public CommonProperties Guide_Rail { get; set; }
        public CommonProperties Guard_Technical_Data_Sheet_For_Ksbase { get; set; }
        public CommonProperties Guardtext { get; set; }
        public CommonProperties Globe_Valve { get; set; }
        public CommonProperties General_Information { get; set; }
        public CommonProperties General_Description { get; set; }
        public CommonProperties General { get; set; }
        public CommonProperties Function_Single_Pump { get; set; }
        public CommonProperties Function_Double_Pump { get; set; }
        public CommonProperties Functional_Test_Addition { get; set; }
        public CommonProperties Functional_Test { get; set; }
        public CommonProperties Force_Text_Note { get; set; }
        public CommonProperties Force_Moment { get; set; }
        public CommonProperties Force_Drawing_Note { get; set; }
        public CommonProperties Force_And_Moment { get; set; }
        public CommonProperties Flow_Generation { get; set; }
        public CommonProperties Flang_Dmnsn_Data_Sht { get; set; }
        public CommonProperties Flange_Standard { get; set; }
        public CommonProperties Flange_Pressure { get; set; }
        public CommonProperties Final_Visual_Inspection_Witnessed { get; set; }
        public CommonProperties Final_Visual_Inspection { get; set; }
        public CommonProperties Final_Inspection { get; set; }
        public CommonProperties Film_Thickness_Test { get; set; }
        public CommonProperties Fallback_Information_Note { get; set; }
        public CommonProperties Exterior_Coating { get; set; }
        public CommonProperties Explosion_Protection { get; set; }
        public CommonProperties Execution_Submersible_Mixer { get; set; }
        public CommonProperties Etanorm_Description { get; set; }
        public CommonProperties Enquiry_No { get; set; }
        public CommonProperties Electrical_Test_Motor { get; set; }
        public CommonProperties Electrical_Data { get; set; }
        public CommonProperties Electrical_Connection_Cable { get; set; }
        public CommonProperties Duckfoot { get; set; }
        public CommonProperties Driver { get; set; }
        public CommonProperties Drawing_Note { get; set; }
        public CommonProperties Document_Version { get; set; }
        public CommonProperties Documentssendseparately { get; set; }
        public CommonProperties Documentname { get; set; }
        public CommonProperties Documentationoutput { get; set; }
        public CommonProperties Documentationchecklist { get; set; }
        public CommonProperties Dn_Nps { get; set; }
        public CommonProperties Discharge_Side { get; set; }
        public CommonProperties Discharge_Flange { get; set; }
        public CommonProperties Discharge_Cover { get; set; }
        public CommonProperties Dimensions_Control_Unit { get; set; }
        public CommonProperties Dimensioningpoint { get; set; }
        public CommonProperties Dimensional_Visual_Inspection_Witnessed { get; set; }
        public CommonProperties Dimensional_Visual_Inspection { get; set; }
        public CommonProperties Dimensionaltolerancestext { get; set; }
        public CommonProperties Determination_Of_Film_Thickness { get; set; }
        public CommonProperties Design_Data_Pump { get; set; }
        public CommonProperties Design_Data { get; set; }
        public CommonProperties Designation { get; set; }
        public CommonProperties Design { get; set; }
        public CommonProperties Delivery_Completness_Test { get; set; }
        public CommonProperties Datasheet_Note { get; set; }
        public CommonProperties Datasheet { get; set; }
        public CommonProperties D { get; set; }
        public CommonProperties Customer_Request { get; set; }
        public CommonProperties Customername { get; set; }
        public CommonProperties Customer { get; set; }
        public CommonProperties Curve_Data { get; set; }
        public CommonProperties Coupling_Guard { get; set; }
        public CommonProperties Coupling { get; set; }
        public CommonProperties Countryname { get; set; }
        public CommonProperties Corrosion_Protection { get; set; }
        public CommonProperties Correction_Viscosity { get; set; }
        public CommonProperties Content { get; set; }
        public CommonProperties Connection_Standard { get; set; }
        public CommonProperties Connection_Plan { get; set; }
        public CommonProperties Connections { get; set; }
        public CommonProperties Conflict_Note { get; set; }
        public CommonProperties Configured { get; set; }
        public CommonProperties Companyname { get; set; }
        public CommonProperties Compact_Datasheet_Valve { get; set; }
        public CommonProperties Compact_Datasheet_Control_Unit { get; set; }
        public CommonProperties Compact_Datasheet { get; set; }
        public CommonProperties Coloring_Surface_Finish { get; set; }
        public CommonProperties Coating_Tests { get; set; }
        public CommonProperties Coating_Inspection { get; set; }
        public CommonProperties Closure_Test { get; set; }
        public CommonProperties Claw { get; set; }
        public CommonProperties City_Postalcode { get; set; }
        public CommonProperties Choice_Of_The_Bidder { get; set; }
        public CommonProperties Chemical_Analysis { get; set; }
        public CommonProperties Characteristics { get; set; }
        public CommonProperties Certifications { get; set; }
        public CommonProperties Certificate { get; set; }
        public CommonProperties Casing_Cover { get; set; }
        public CommonProperties Bt3_Note { get; set; }
        public CommonProperties Body_Pressure_Test { get; set; }
        public CommonProperties Bearing_Temperature_Test { get; set; }
        public CommonProperties Bearing_Bracket { get; set; }
        public CommonProperties Bearing { get; set; }
        public CommonProperties Basin { get; set; }
        public CommonProperties Baseplate_Cupling_Bearing { get; set; }
        public CommonProperties Baseplate { get; set; }
        public CommonProperties Balancing_Test_Shaft { get; set; }
        public CommonProperties Balancing_Test_Rotor { get; set; }
        public CommonProperties Balancing_Test_Impeller { get; set; }
        public CommonProperties Balancing_Test_Coupling { get; set; }
        public CommonProperties Balancing_Test { get; set; }
        public CommonProperties Back_Seat_Test { get; set; }
        public CommonProperties Auxiliary_Connections_Pump { get; set; }
        public CommonProperties Aucustic_Test { get; set; }
        public CommonProperties Amarexcadenastext { get; set; }
        public CommonProperties Alternative { get; set; }
        public CommonProperties Aggregate { get; set; }
        public CommonProperties Additional_Special_Execution { get; set; }
        public CommonProperties Additionaldocumentation { get; set; }
        public CommonProperties Actuator { get; set; }
        public CommonProperties Accessories_And_Service { get; set; }
        public CommonProperties Accessories { get; set; }
        public CommonProperties Acceptance_Test_Pumps { get; set; }
        public CommonProperties Acceptance_Test_Finished_Parts_Pumps { get; set; }
        public CommonProperties Acceptance_Tests_Certificates_Unmachined_Parts { get; set; }
        public CommonProperties Acceptance_Tests_Certificates_Product_Test_Pumps { get; set; }
        public CommonProperties Acceptance_Tests_Certificates_Product_Test_Of_Finished_Part_Pumps { get; set; }
        public CommonProperties Acceptance_Standard { get; set; }

    }
    public class CommonProperties
    {
        public string Lang { get; set; }
        public string Value { get; set; }
    }

}
